[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "stick"
version = "0.1.0"
description = "Plays sounds when triggered by piezo sensors"
requires-python = ">=3.8"
